 /******************************************************************************
 *
 * Module: Port
 *
 * File Name: Port_PBcfg.c
 *
 * Description: Post Build Configuration Source file for TM4C123GH6PM Microcontroller - Port Driver
 *
 * Author: Mohamed Khaled Mohamed Radi 
 *
 ******************************************************************************/

/******************************************************************************
 *                             AR and SW Versions                             *
 ******************************************************************************/
/*
 * Module Version 1.0.0
 */
#define PORT_PBCFG_SW_MAJOR_VERSION              (1U)
#define PORT_PBCFG_SW_MINOR_VERSION              (0U)
#define PORT_PBCFG_SW_PATCH_VERSION              (0U)

/*
 * AUTOSAR Version 4.0.3
 */
#define PORT_PBCFG_AR_RELEASE_MAJOR_VERSION     (4U)
#define PORT_PBCFG_AR_RELEASE_MINOR_VERSION     (0U)
#define PORT_PBCFG_AR_RELEASE_PATCH_VERSION     (3U)

/******************************************************************************
 *            Include module header file and apply Version Checking           *
 ******************************************************************************/
#include "Port.h"

/* AUTOSAR Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_AR_RELEASE_MAJOR_VERSION != PORT_AR_RELEASE_MAJOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_MINOR_VERSION != PORT_AR_RELEASE_MINOR_VERSION)\
 ||  (PORT_PBCFG_AR_RELEASE_PATCH_VERSION != PORT_AR_RELEASE_PATCH_VERSION))
  #error "The AR version of PBcfg.c does not match the expected version"
#endif

/* Software Version checking between Dio_PBcfg.c and Dio.h files */
#if ((PORT_PBCFG_SW_MAJOR_VERSION != PORT_SW_MAJOR_VERSION)\
 ||  (PORT_PBCFG_SW_MINOR_VERSION != PORT_SW_MINOR_VERSION)\
 ||  (PORT_PBCFG_SW_PATCH_VERSION != PORT_SW_PATCH_VERSION))
  #error "The SW version of PBcfg.c does not match the expected version"
#endif

/******************************************************************************
 *                   PB structure used with Port_Init API                  *
 ******************************************************************************/
const  Port_ConfigType Port_Configuration = 
{
    /*port_num, pin_num, Port_Pin_Direction, Port_Pin_Direction_Changeable, mode, 
      Port_PinLevelValue, Port_Pin_Mode_Changeable, resistor*/ 
    /* Port A */
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_0_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 0 */ /* INDEX 0 */
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_1_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 1 */ /* INDEX 1 */ 
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_2_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 2 */ /* INDEX 2 */ 
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_3_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 3 */ /* INDEX 3 */ 
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_4_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 4 */ /* INDEX 4 */ 
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_5_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 5 */ /* INDEX 5 */ 
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_6_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 6 */ /* INDEX 6 */ 
    { PORTCONFIG_PORT_A_NUM, PORTCONFIG_PIN_7_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 7 */ /* INDEX 7 */ 
    /* Port B */
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_0_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 0 */ /* INDEX 8 */ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_1_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 1 */ /* INDEX 9*/ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_2_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 2 */ /* INDEX 10 */ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_3_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 3 */ /* INDEX 11 */ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_4_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 4 */ /* INDEX 12 */ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_5_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 5 */ /* INDEX 13 */ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_6_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 6 */ /* INDEX 14 */ 
    { PORTCONFIG_PORT_B_NUM, PORTCONFIG_PIN_7_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 7 */ /* INDEX 15 */ 
    /* Port C */ /* PC0 : PC3 reserved for JTAG*/
    { PORTCONFIG_PORT_C_NUM, PORTCONFIG_PIN_4_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 4 */ /* INDEX 16 */ 
    { PORTCONFIG_PORT_C_NUM, PORTCONFIG_PIN_5_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 5 */ /* INDEX 17 */ 
    { PORTCONFIG_PORT_C_NUM, PORTCONFIG_PIN_6_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 6 */ /* INDEX 18 */ 
    { PORTCONFIG_PORT_C_NUM, PORTCONFIG_PIN_7_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 7 */ /* INDEX 19 */ 
     /* Port D */
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_0_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 0 */ /* INDEX 20 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_1_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 1 */ /* INDEX 21 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_2_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 2 */ /* INDEX 22 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_3_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 3 */ /* INDEX 23 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_4_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 4 */ /* INDEX 24 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_5_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 5 */ /* INDEX 25 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_6_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 6 */ /* INDEX 26 */ 
    { PORTCONFIG_PORT_D_NUM, PORTCONFIG_PIN_7_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 7 */ /* INDEX 27 */ 
    /* Port E */
    { PORTCONFIG_PORT_E_NUM, PORTCONFIG_PIN_0_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 0 */ /* INDEX 28 */ 
    { PORTCONFIG_PORT_E_NUM, PORTCONFIG_PIN_1_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 1 */ /* INDEX 29 */ 
    { PORTCONFIG_PORT_E_NUM, PORTCONFIG_PIN_2_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 2 */ /* INDEX 30 */ 
    { PORTCONFIG_PORT_E_NUM, PORTCONFIG_PIN_3_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 3 */ /* INDEX 31 */ 
    { PORTCONFIG_PORT_E_NUM, PORTCONFIG_PIN_4_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 4 */     /* INDEX 32 */ 
   { PORTCONFIG_PORT_E_NUM, PORTCONFIG_PIN_5_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 5 */  /* INDEX 33 */ 
    /* Port F */
    { PORTCONFIG_PORT_F_NUM, PORTCONFIG_PIN_0_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 0 */ /* INDEX 34 */ 
    { PORTCONFIG_PORT_F_NUM, PORTCONFIG_PIN_1_NUM, PORT_PIN_OUT, STD_ON, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, OFF } /* PIN 1 */ /* LED1 */ /* INDEX 35 */ 
    { PORTCONFIG_PORT_F_NUM, PORTCONFIG_PIN_2_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 2 */ /* INDEX 36 */ 
    { PORTCONFIG_PORT_F_NUM, PORTCONFIG_PIN_3_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 3 */ /* INDEX 37 */ 
    { PORTCONFIG_PORT_F_NUM, PORTCONFIG_PIN_4_NUM, PORT_PIN_IN, STD_OFF, PORTCONFIG_PIN_MODE_DIO,
      PORT_PIN_LEVEL_HIGH, STD_ON, PULL_UP } /* PIN 4 */ /* SW1 */ /* INDEX 38 */ 
}